# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

40.times do
  User.create(
    username: Faker::Internet.user_name,
    email: Faker::Internet.email,
    password: Faker::Internet.password
  ) 
end 


shoes = [
  ["Under Armour Men's Stephen Curry Low Basketball Shoes", "109.99", "Navy / Yellow", "Under Armour", "app/assets/images/seed1.jpg", "Stay flexible and quick on your feet in the new low-top version of the Under Armour® Curry Charged Foam basketball shoes. Thanks to the low-cut ankle design, the Curry 1 allows for a full range of motion. A Charged Foam midsole adapts with each move - soft and flexible during slow motion, but firm and responsive during fast movements. An ideal game shoe for summer games, the Curry low keeps you cool and comfortable when the action heats up."],
  ["Under Armour Men's Stephen Curry Low Basketball Shoes", "109.99", "Turquoise / Black", "Under Armour", "app/assets/images/seed2.jpg", "Stay flexible and quick on your feet in the new low-top version of the Under Armour® Curry Charged Foam basketball shoes. Thanks to the low-cut ankle design, the Curry 1 allows for a full range of motion. A Charged Foam midsole adapts with each move - soft and flexible during slow motion, but firm and responsive during fast movements. An ideal game shoe for summer games, the Curry low keeps you cool and comfortable when the action heats up."],
  ["Jordan Men's Air Jordan 5 Retro Basketball Shoes", "189.99", "White / Green", "Air Jordan", "app/assets/images/seed3.jpg", ""],
  ["Nick Men's Kyrie 1 Basketball Shoes", "109.99", "Blue / Crimson / White", "Nike", "app/assets/images/seed4.jpg", "If you're quick on your feet like Irving, the Nike® Kyrie 1 basketball shoe is perfect for your game. Combining lightweight, zonal support with responsive cushioning, this on-court shoe is built for forward motion. Hyperfuse construction is durable yet breathable, offering the perfect design for support and stability. Lightweight foam throughout the midsole provides comfortable cushioning, while the unique outsole pattern enhances traction."],
  ["Nike Men's Kobe X Basketball Shoes", "179.99", "University Red / Photo Blue", "Nike", "app/assets/images/seed5.jpg", "Change the game when you step out in the Nike® Kobe X basketball shoe. Incorporating unique elements from past models, the X makes a breakthrough with new technology. Responsive Lunarlon foam with flex grooves enhances natural motion, while a visible 180-degree Zoom Air unit in the heel increases responsiveness. An updated, transparent design symbolizes Kobe's life and sophisticated game, making this the perfect shoe to respect his style."],
  ["Nike Men's Zoom HyperRev 2015 Basketball Shoes", "89.99", "Black / White/Metallic Gold", "Nike", "app/assets/images/seed6.jpg", "Get equipped for championship performance with the Nike® Zoom HyperRev 2015 basketball shoe. Delivering optimal stability, this on-court shoe features a lightweight outer shell that provides zonal support and durability. A breathable inner bootie maximizes airflow while providing a close, comfortable fit. Hyperfuse construction increases lockdown support, while the thick rubber outsole features a herringbone pattern for improved traction."],
  ["Nike Men's KD VIII Basketball Shoes", "179.99", "Navy / Red/White", "Nike", "app/assets/images/seed7.jpg", "Updated with FlyWeave technology, the all-new Nike® KD 8 basketball shoe keeps you looking fresh on the court. Thanks to the unique Flywire construction, the 8 is Kevin Durant's lightest shoe to date. The woven upper increases breathability while still providing lockdown support. A Zoom Air cushioning system throughout the midsole adds comfort, giving you full control and plush responsiveness. Up your style game with Durant's latest shoe."],
  ["Nike Men's Kyrie 1 Basketball Shoes", "109.99", "Tour Yellow / Teal/Universi", "Nike", "app/assets/images/seed8.jpg", "If you're quick on your feet like Irving, the Nike® Kyrie 1 basketball shoe is perfect for your game. Combining lightweight, zonal support with responsive cushioning, this on-court shoe is built for forward motion. Hyperfuse construction is durable yet breathable, offering the perfect design for support and stability. Lightweight foam throughout the midsole provides comfortable cushioning, while the unique outsole pattern enhances traction."],
  ["Nike Men's Zoom HyperRev 2015 Basketball Shoes", "89.99", "Blue / Silver", "Nike", "app/assets/images/seed9.jpg", "Get equipped for championship performance with the Nike® Zoom HyperRev 2015 basketball shoe. Delivering optimal stability, this on-court shoe features a lightweight outer shell that provides zonal support and durability. A breathable inner bootie maximizes airflow while providing a close, comfortable fit. Hyperfuse construction increases lockdown support, while the thick rubber outsole features a herringbone pattern for improved traction."],
  ["Nike Men's Lebron 12 Basketball Shoes", "199.99", "White / Turquoise", "Nike", "app/assets/images/seed10.jpg", "Unlike anything you've ever worn before, the Nike® LeBron XII is a revolutionary game shoe. For the first time ever, the 12 features hexagonal Nike® Zoom pods that move independently for flexible cushioning and superior traction. New Megafuse technology, an evolution of the popular Hyperfuse, compartmentalizes layers to make the shoe as light and durable as possible. With LeBron's name on the tongue, you can sport The Twelve with pride."],
  ["Nick Men's Kyrie 1 Basketball Shoes", "109.99", "Berry / Hot Lava / Black", "Nike", "app/assets/images/seed11.jpg", "If you're quick on your feet like Irving, the Nike® Kyrie 1 basketball shoe is perfect for your game. Combining lightweight, zonal support with responsive cushioning, this on-court shoe is built for forward motion. Hyperfuse construction is durable yet breathable, offering the perfect design for support and stability. Lightweight foam throughout the midsole provides comfortable cushioning, while the unique outsole pattern enhances traction."],
  ["Nike Men's KD Trey 5 II Basketball Shoes", "79.99", "Grey / Green", "Nike", "app/assets/images/seed12.jpg", "Step up to any on-court challenge with confidence in the Nike® KD Trey 5 II basketball shoe. Giving KD the ability to play in any condition, this signature shoe was designed to withstand outdoor play. The ultra-lightweight mesh upper improves breathability, while the Nike® Zoom Unit in the forefoot allows for low-profile responsiveness. Added Flywire technology enhances stability, making the Trey 5 II the perfect choice for intense games."],
  ["Nike Men's Zoom HyperRev 2015 Basketball Shoes", "89.99", "Black / Metallic Silver", "Nike", "app/assets/images/seed13.jpg", "Get equipped for championship performance with the Nike® Zoom HyperRev 2015 basketball shoe. Delivering optimal stability, this on-court shoe features a lightweight outer shell that provides zonal support and durability. A breathable inner bootie maximizes airflow while providing a close, comfortable fit. Hyperfuse construction increases lockdown support, while the thick rubber outsole features a herringbone pattern for improved traction."],
  ["Nike Men's Zoom HyperRev 2015 Basketball Shoes", "89.99", "Midnight Navy / Tour Yellow", "Nike", "app/assets/images/seed14.jpg", "Get equipped for championship performance with the Nike® Zoom HyperRev 2015 basketball shoe. Delivering optimal stability, this on-court shoe features a lightweight outer shell that provides zonal support and durability. A breathable inner bootie maximizes airflow while providing a close, comfortable fit. Hyperfuse construction increases lockdown support, while the thick rubber outsole features a herringbone pattern for improved traction."],
  ["Nike Men's KB Mentality Basketball Shoes", "109.99", "Blue / Royal", "Nike", "app/assets/images/seed15.jpg", "Designed to meet the intense demands of Kobe Bryant's game, the Nike® KB Mentality basketball shoe gets you geared up for greatness. The low-top design allows for an optimizing range of ankle motion, while the drop-in Lunarlon foam midsole delivers responsive cushioning. A unique Kobe 'shealth' logo overlay is featured on the forefoot to add support. Weighing in at only 9.9 ounces, this lightweight shoe is the perfect on-court choice."],
  ["Nike Men's KD VII Basketball Shoes", "119.99", "Grey", "Nike", "app/assets/images/seed16.jpg", "Updated with FlyWeave technology, the all-new Nike® KD 8 basketball shoe keeps you looking fresh on the court. Thanks to the unique Flywire construction, the 8 is Kevin Durant's lightest shoe to date. The woven upper increases breathability while still providing lockdown support. A Zoom Air cushioning system throughout the midsole adds comfort, giving you full control and plush responsiveness. Up your style game with Durant's latest shoe."],
  ["Nike Men's Zoom LeBron Soldier VIII Basketball Shoes", "109.99", "Red / White", "Nike", "app/assets/images/seed17.jpg", "Stand up to any on-court challenge with the Nike® Zoom Soldier VIII basketball shoe. Key updates include a new zipper closure under the midfoot strap, locking your foot into place to reduce slipping and improve stability. The Soldier 8 has exceptional protection and responsiveness specifically crafted for the versatile player. A decoupled forefoot and heel allow a natural foot flex, while a power-flex traction pattern grips the court below."],
  ["Nike Men's Prime Hype DF Basketball Shoes", "99.99", "Black", "Nike", "app/assets/images/seed18.jpg", "Lace up and take the court by storm in the Nike® Prime Hype DF basketball shoe. Designed for fast-paced, multi-directional movement, the Prime Hype features innovative cushioning so you can take your game to the next level. A breathe tech upper increases airflow while adding support, and the dual-density foam midsole serves as a full-length cushion. The data-informed rubber outsole enhances traction so you can bring your best game."],
  ["Nike Men's LeBron 12 Low Basketball Shoes", "174.99", "Grey / Blue", "Nike", "app/assets/images/seed19.jpg", "Unlike anything you've ever worn before, the Nike® LeBron XII is a revolutionary game shoe. For the first time ever, the 12 features hexagonal Nike® Zoom pods that move independently for flexible cushioning and superior traction. New Megafuse technology, an evolution of the popular Hyperfuse, compartmentalizes layers to make the shoe as light and durable as possible. With LeBron's name on the tongue, you can sport The Twelve with pride."],
  ["Nike Men's Kyrie 1 Basketball Shoes", "109.99", " Emerald / Metallic Silver", "Nike", "app/assets/images/seed20.jpg", "If you're quick on your feet like Irving, the Nike® Kyrie 1 basketball shoe is perfect for your game. Combining lightweight, zonal support with responsive cushioning, this on-court shoe is built for forward motion. Hyperfuse construction is durable yet breathable, offering the perfect design for support and stability. Lightweight foam throughout the midsole provides comfortable cushioning, while the unique outsole pattern enhances traction."],
  ["Nike Men's Overplay VIII Basketball Shoes", "54.99", "Black / Anthracite", "Nike", "app/assets/images/seed21.jpg", "Classic, sporty and stylish the Nike® Men's Overplay VII basketball shoe is perfect for casual or performance wear. Breathe tech uses bonded layers of TPU and mesh in the upper, offering a lightweight and breathable design to keep your feet comfortable. Head down to the court for a quick pick-up game as the TPU midfoot shank enhances support through the arch. Solid rubber included on the outsole for durable traction."],
  ["Nike Men's Overplay VIII Basketball Shoes", "54.99", "Black / Anthracite", "Nike", "app/assets/images/seed22.jpg", "Classic, sporty and stylish the Nike® Men's Overplay VII basketball shoe is perfect for casual or performance wear. Breathe tech uses bonded layers of TPU and mesh in the upper, offering a lightweight and breathable design to keep your feet comfortable. Head down to the court for a quick pick-up game as the TPU midfoot shank enhances support through the arch. Solid rubber included on the outsole for durable traction."],
  ["Nike Men's Prime Hype DF Basketball Shoes", "69.99", "Black", "Nike", "app/assets/images/seed23.jpg", "Lace up and take the court by storm in the Nike® Prime Hype DF basketball shoe. Designed for fast-paced, multi-directional movement, the Prime Hype features innovative cushioning so you can take your game to the next level. A breathe tech upper increases airflow while adding support, and the dual-density foam midsole serves as a full-length cushion. The data-informed rubber outsole enhances traction so you can bring your best game."],
  ["Nike Men's KB Mentality Basketball Shoes", "99.99", "Blue / Royal", "Nike", "app/assets/images/seed24.jpg", "Designed to meet the intense demands of Kobe Bryant's game, the Nike® KB Mentality basketball shoe gets you geared up for greatness. The low-top design allows for an optimizing range of ankle motion, while the drop-in Lunarlon foam midsole delivers responsive cushioning. A unique Kobe 'shealth' logo overlay is featured on the forefoot to add support. Weighing in at only 9.9 ounces, this lightweight shoe is the perfect on-court choice."],
  ["Nike Men's Zoom LeBron Soldier VIII Basketball Shoes", "119.99", "Black / Grey", "Nike", "app/assets/images/seed25.jpg", "Stand up to any on-court challenge with the Nike® Zoom Soldier VIII basketball shoe. Key updates include a new zipper closure under the midfoot strap, locking your foot into place to reduce slipping and improve stability. The Soldier 8 has exceptional protection and responsiveness specifically crafted for the versatile player. A decoupled forefoot and heel allow a natural foot flex, while a power-flex traction pattern grips the court below."],
  ["Nike Men's LeBron 12 Low Basketball Shoes", "174.99", "Grey / Blue", "Nike", "app/assets/images/seed26.jpg", "Unlike anything you've ever worn before, the Nike® LeBron XII is a revolutionary game shoe. For the first time ever, the 12 features hexagonal Nike® Zoom pods that move independently for flexible cushioning and superior traction. New Megafuse technology, an evolution of the popular Hyperfuse, compartmentalizes layers to make the shoe as light and durable as possible. With LeBron's name on the tongue, you can sport The Twelve with pride."],
  ["Nike Men's Kobe X Basketball Shoes", "179.99", "Teal / Orange", "Nike", "app/assets/images/seed27.jpg", "Change the game when you step out in the Nike® Kobe X basketball shoe. Incorporating unique elements from past models, the X makes a breakthrough with new technology. Responsive Lunarlon foam with flex grooves enhances natural motion, while a visible 180-degree Zoom Air unit in the heel increases responsiveness. An updated, transparent design symbolizes Kobe's life and sophisticated game, making this the perfect shoe to respect his style."],
  ["Nike Men's Zoom HyperRev 2015 Basketball Shoes", "89.99", "White / Black", "Nike", "app/assets/images/seed28.jpg", "Get equipped for championship performance with the Nike® Zoom HyperRev 2015 basketball shoe. Delivering optimal stability, this on-court shoe features a lightweight outer shell that provides zonal support and durability. A breathable inner bootie maximizes airflow while providing a close, comfortable fit. Hyperfuse construction increases lockdown support, while the thick rubber outsole features a herringbone pattern for improved traction."],
  ["Nike Men's Air Visi Pro V NBK Basketball Shoes", "69.99", "Black / Anthracite", "Nike", "app/assets/images/seed29.jpg", "Get the edge over your opponent when you wear the Nike® Air Visi Pro V basketball shoe. The upper features Nubuck and synthetic leather for support with a premium look, offering exceptional style and comfort. Cruise down the court while the Air units in the heel absorb impact and outriggers enhance stability. The outsole includes a modified herringbone traction pattern for durability and traction during explosive plays."],
  ["Nike Men's Zoom LeBron Soldier VIII Basketball Shoes", "109.99", "Red / Black", "Nike", "app/assets/images/seed30.jpg", "Stand up to any on-court challenge with the Nike® Zoom Soldier VIII basketball shoe. Key updates include a new zipper closure under the midfoot strap, locking your foot into place to reduce slipping and improve stability. The Soldier 8 has exceptional protection and responsiveness specifically crafted for the versatile player. A decoupled forefoot and heel allow a natural foot flex, while a power-flex traction pattern grips the court below."],
  ["Nike Men's Kobe X Basketball Shoes", "174.99", "Grey / Silver", "Nike", "app/assets/images/seed22.jpg", "Change the game when you step out in the Nike® Kobe X basketball shoe. Incorporating unique elements from past models, the X makes a breakthrough with new technology. Responsive Lunarlon foam with flex grooves enhances natural motion, while a visible 180-degree Zoom Air unit in the heel increases responsiveness. An updated, transparent design symbolizes Kobe's life and sophisticated game, making this the perfect shoe to respect his style."]
]

shoes.each do |array|
  Shoe.create(name: array[0], price: array[1], color: array[2], brand: array[3], image: File.new(array[4]), description: array[5])
end

stores = [
  "Foot Locker", 
  "Amazon",
  "Nike",
  "Adidas",
  "Puma",
  "Cole Haan",
  "Reebok",
  "Under Armour"
]

stores.each do |store|
  Store.create!(
    store_name: store
  )
end




50.times do
  ShoeStore.create!(
    shoe: Shoe.all.sample,
    store: Store.all.sample,
    url: "http://www.danelsonrosa.com"
  )
end